### ISSUE TITLE
Cant find proto files

### ISSUE THREAD

**Issue by cheuerde** [meztez/bigrquerystorage#16]
Hi, I have an issue regarding the proto include files that are not being found.
Those messages I am getting:

google/api/http.proto: No such file or directory
google/cloud/bigquery/storage/v1/storage.proto: No such file or directory

I have already modified the proto_path in `tools/config/cofnigure.R`, but no matter where I put the proto include files or how I specify
the path, it never finds the files. Any ideas on how to solve this?

Also, I had to install these ubuntu packages to get the proto/grpc dependencies:

libprotobuf-dev protobuf-compiler-grpc libgrpc++-dev

Thanks!

**Comment by meztez** [comment]
@cheuerde What did you execute to run into this issue?

**Comment by cheuerde** [comment]
I ran: remotes::install_github("meztez/bigrquerystorage")

I also cloned the repository (and edited the configure.R file) and tried to install that way, but same result

**Comment by meztez** [comment]
Did you run : https://github.com/meztez/bigrquerystorage#debianubuntu ?

```
# install protoc and grpc
apt-get install build-essential autoconf libtool pkg-config
git clone -b v1.33.2 https://github.com/grpc/grpc
cd grpc
git submodule update --init
./test/distrib/cpp/run_distrib_test_cmake_module_install_pkgconfig.sh
cd ..
rm -R grpc
```

**Comment by cheuerde** [comment]
Yes, did all that on my machine (Ubuntu 18.04) but wasnt enough, so I also installed these packages:

```sh
libprotobuf-dev protobuf-compiler-grpc libgrpc++-dev
```

And then the only problem left are the missing proto files - they are not missing, the proto compiler just cant find them

**Comment by meztez** [comment]
I'll have to rebuild an environment to debug it. Thanks for reporting it. I'll let you know what I find.

**Comment by cheuerde** [comment]
Thanks a lot!

**Comment by meztez** [comment]
@cheuerde I had to install arrow from

```
Iinstall.packages("cpp11")
install.packages("arrow", repos = "https://arrow-r-nightly.s3.amazonaws.com")
```

and add to the instruction for R curl package to install.

```
apt install libcurl4-openssl-dev
```

Otherwise the instructions work for me.

@cheuerde  Are you running on a 32bits system?

**Comment by cheuerde** [comment]
So, on a clean installation of Ubuntu 18.04 (64bit) I got everything installed and working.
Thanks a lot for looking into this!
