### ISSUE TITLE
On Debian with R4.1.3 - unable to install

### ISSUE THREAD

**Issue by Stephen-McDaniel** [meztez/bigrquerystorage#17]
Docker image: rocker/geospatial:4.1.3

Running:
```
Sys.setenv("NOT_CRAN"=TRUE) # To avoid long arrow compile time
remotes::install_github("meztez/bigrquerystorage")
```
Yields:
```
* installing *source* package ‘bigrquerystorage’ ...
** using staged installation
** preparing to configure package 'bigrquerystorage' ...
*** searching for protoc ... OK
*** searching for grpc_cpp_plugin ... Failed
Error in detect_binary("grpc_cpp_plugin") : 
  Could not find grpc_cpp_plugin
Calls: source_file -> eval -> eval -> detect_binary
Execution halted
ERROR: configuration failed for package ‘bigrquerystorage’
* removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/4.1/bigrquerystorage’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpgiJoqb/file13d684c191a/bigrquerystorage_0.5.0.tar.gz’ had non-zero exit status
```

Thanks,
Stephen

**Comment by Stephen-McDaniel** [comment]
My apologies for missing this. Got it working and about 7x faster than bigrquery. A huge improvement with some very large data pulls! 🎉

Just one quick question, is this likely safe for production use? I only ask after seeing you discussed moving this package to CRAN a while back but hesitated. Is this likely more of an install matrix issue or execution concern (once installed)?

**Comment by meztez** [comment]
The system requirements are too complicated for CRAN and I'm not willing to maintain an installation file. We have been using it in production for the past 3ish years. I remember encountering issues while trying to replicate database using this. Some segfault when more than 1.5ish TB of memory has to be allocated to handle table download.

So, if your data fits in memory, you are ok. If not, it is better to export to parquet export, something like :

```r
      bigrquery::bq_table_save(
        x = {table},
        destination_uris = sprintf("gs://%s/%s_*.parquet", {bucket}, {dt_name}),
        destination_format = "PARQUET",
        billing = "{gcp-billing-project}",
        compression = "SNAPPY",
        location = "{location}",
        quiet = TRUE
      )
      # Empty bucket on exit if you want
      on.exit(
        system(
          sprintf("gsutil -m rm -r gs://%s/\\*", {bucket}),
          ignore.stdout = TRUE,
          ignore.stderr = TRUE
        ),
        add = TRUE
      )
      
      # Import file on local virtual machine temporary directory
      system(
        sprintf("gsutil -m cp gs://%s/%s_* %s/", {bucket}, {dt_name}, {tmpdir}),
        ignore.stdout = TRUE,
        ignore.stderr = TRUE
      )
```

Note that it would require having google cloud sdk installed.

**Comment by Stephen-McDaniel** [comment]
I totally appreciate the situation and thanks again for all the insight!
