### ISSUE TITLE
Abandon the `tools/config.R`

### ISSUE THREAD

**Issue by gaborcsardi** [meztez/bigrquerystorage#28]
It is not a bad idea to configure the build from R, and I am not a big fan of Makefiles, but unfortunately the current setup is very different from the usual setup, and this makes things challenging. 

Here is an example. Detecting and running `pkg-config` is hard on Windows, because Rtools43 does not have `pkg-config.exe`, only `pkg-config` which is a shell script:
```
> Sys.which("pkg-config")
pkg-config
        ""
> system('sh -c "which pkg-config"')
/x86_64-w64-mingw32.static.posix/bin/pkg-config
```

Another example. Writing files defaults to Windows EOL characters, so we end up with this in `R CMD check`:
```
Found the following sources/headers with CR or CRLF line endings:
  src/google/api/annotations.pb.cc
  src/google/api/annotations.pb.h
  src/google/api/client.pb.cc
  src/google/api/client.pb.h
  src/google/api/field_behavior.pb.cc
  src/google/api/field_behavior.pb.h
  src/google/api/http.pb.cc
  src/google/api/http.pb.h
  src/google/api/launch_stage.pb.cc
...
```

I don't think this is very urgent, I'll be able to make the Windows build work with the current setup, I think.

**Comment by meztez** [comment]
@gaborcsardi Any direction you would recommend to replacing it?

**Comment by gaborcsardi** [comment]
Have a plain `configure` shell script, not autotools, and the shell script can call R scripts in `tools/` to do some specific tasks, e.g. download and configure the system libs, as we have the R code for that already, and easier to do it in R.

I think the arrow `configure` is overkill, and we also don't need a separate `configure.win`, we can do everything from a single `configure`. 

I think the logic of `configure.R` is fine, btw. Something close to https://github.com/jeroen/curl/blob/master/configure would be fine I think.

Also, I would move the proto files into `src/` and run `protoc` from `Makevars`. Currently we always recompile the proto files, and thus always recompile the whole package. We can trust `make` to recompile as needed.

It would be also nice to have this before CRAN submission, because otherwise we can't (easily) use the new `pkg-config` in Rtools43. But of course Rtools43 does not have grpc, so it is also not crucial.

**Comment by meztez** [comment]
Adding it to stack. Thanks for everything you've contributed so far.

**Comment by meztez** [comment]
[like]  Bruno Tremblay reacted to your message:
________________________________
