### ISSUE TITLE
`env_unlock()` will be removed from rlang

### ISSUE THREAD

**Issue by lionel-** [meztez/bigrquerystorage#57]
Hello, just a heads up that we'll remove `env_unlock()` from rlang in a future version (undetermined timeline as of yet) because it's implemented using non-API calls that CRAN has started to lint. Could you try and find another approach please?

**Comment by meztez** [comment]
Thanks for the heads-up @lionel-, work is already ongoing on this front to better interface with bigrquery package. The feature will be entirely dropped.

**Comment by hadley** [comment]
Done in #52 so this issue can be closed.
