### ISSUE TITLE
bigrquerystorage dependencies

### ISSUE THREAD

**Issue by stickfighter342** [meztez/bigrquerystorage#59]
Would like to ask what the version of the dependencies for bigrquerystorage are, as I am unfamiliar with R and the versions of the dependencies are not given here: https://cran.r-project.org/web/packages/bigrquerystorage/index.html.

**Comment by meztez** [comment]
For Ubuntu, the actions of this repos uses 
```
 sudo apt-get install -y libprotobuf-dev protobuf-compiler-grpc libgrpc++-dev
```
For Mac
```
brew install grpc --fetch-HEAD
```
https://github.com/meztez/bigrquerystorage/blob/main/.github/workflows/R-CMD-check.yaml

If you have issue installing the package, let me know.

**Comment by stickfighter342** [comment]
Thank you for your reply! I was asking about whether there are version requirements of these packages:

arrow, methods, rlang, DBI, bigrquery, assertthat, Rcpp, lifecycle, bit64, tibble

My project is mainly written in R 3.3.1, and I wanted to confirm which version of each package is used so I can determine which version of R to upgrade to, or whether upgrading is unnecessary.

**Comment by meztez** [comment]
I do not know. Best way to know is to try. I have not tested this far back. That's 8 years ago, gRPC was not released yet.

**Comment by stickfighter342** [comment]
Okay, thank you very much.
