### ISSUE TITLE
Not compiling on R 4.2 windows

### ISSUE THREAD

**Issue by hadley** [meztez/bigrquerystorage#63]
e.g. https://github.com/meztez/bigrquerystorage/actions/runs/10961119434/job/30437296344

Any ideas what's going wrong?

**Comment by meztez** [comment]
Might be the grpc tool chain for rtools, will have to reproduce locally.

**Comment by meztez** [comment]
grpc is not included in rtools 4.2

https://github.com/meztez/bigrquerystorage/pull/45#issuecomment-1929965434

We had a fix to download it from the web on install but CRAN rejected the package if it contained it so it was removed.
https://github.com/meztez/bigrquerystorage/blob/7f81f16dc0f87fb96f94d49f3bea7a20d0da6b1f/tools/winlibs.R

**Comment by meztez** [comment]
I've updated the README to reflect the current situation. If it's an issue, we can document how to manually install windows dependencies for R < 4.3 versions.

**Comment by hadley** [comment]
Can we backport the auto-install fix to only work on R 4.2 and earlier? It does make it a bit easier for us, since we try and provide versions that work on R 4.0.0 and later (and people do seem to make use of them).

**Comment by meztez** [comment]
We could, but it does against CRAN policies, so it would be only working on an install from Github.

**Comment by hadley** [comment]
Right, it would never be run on CRAN, but it would (e.g.) be run on https://p3m.dev/ so R users would still easily be able to get binaries for older R versions.

**Comment by meztez** [comment]
I've re-added support for 4.2.

4.1 would need compilation of previous version of grpc to match mingw support in rtools40 and probably a distribution mechanism like the one introduced for 4.2.

That's above what I am able to do at the moment.

Thank you

**Comment by hadley** [comment]
Thank you, it's much appreciated!
