### ISSUE TITLE
downloading FLOATs from bigquery as Integers

### ISSUE THREAD

**Issue by michaelgap360** [meztez/bigrquerystorage#76]
`bqs_table_download` now seems to be downloading all FLOATS in big query tables as integers,

have tried downloading the same table using `bq_table_download` and it worked fine

looks like `bqs_table_download` is returning a tibble by default now, is this converting the columns to integers?

**Comment by meztez** [comment]
Do you have an example I can use to reproduce the problem? What version are you using?

**Comment by michaelgap360** [comment]
I've updated to the latest version (run ran the normal `install.packages("bigrquerystorage")` and it looked like it updated all fine)

as an example

```

upload <- data.table(number =  rnorm(10, mean = 0, sd = 1))
upload$text <- "some_text"

bq_table_upload('TABLE_NAME',
                upload,
                write_disposition='WRITE_TRUNCATE',
                create_disposition='CREATE_IF_NEEDED')



```


`download <- bq_table_download('TABLE_NAME')`

this gives the correct data
![image](https://github.com/user-attachments/assets/50f84006-2dca-40e5-83df-b64afab3522d)


but

`download <- bqs_table_download('TABLE_NAME')`

gives it as an integer
![image](https://github.com/user-attachments/assets/ead1ed5c-1b5d-4e70-af14-c6df2d342511)

**Comment by michaelgap360** [comment]
table in BQ
![image](https://github.com/user-attachments/assets/e69c3a4a-777b-4a07-a72c-a5d9798e33f8)

**Comment by michaelgap360** [comment]
brill thanks

**Comment by meztez** [comment]
Should be fixed on main branch.
